version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: crud_app
    ports:
      - "3306:3306"
    networks:
      - app-network

  node-app:
    build: .
    container_name: node-crud-app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
